#!/usr/bin/env -S perl -CSDA

my ($src, $global_rewrite) = @ARGV;
{ local $/; open my $fh, q[<], $src; $src = <$fh>; close $fh; }
my $code; my $compiled;
$_ = $src;
{ eval $global_rewrite; }
s/^#PP:IN/\$code = <<'PLEOKAK';/gm;
s/^#PP:(OUT|IGN.*)/PLEOKAK/gm;
s/^#PP:COPY\b(.*)/PLEOKAK\n$1\n\$compiled .= \$code;/gm;
s/^#PP:CODE//gm;
$src = $_;
#{ open my $fh, q[>], q[/tmp/kakinv.pl]; print $fh $src; }
eval $src; print $compiled;
