#!/usr/bin/env -S perl -CSDA

my ($src, $global_rewrite) = @ARGV;
{ local $/; open my $fh, q[<], $src; $src = <$fh>; close $fh; }
my $code; my $compiled;
$_ = $src;
{ eval $global_rewrite; }
s/^#PP:(OUT|IGN[[:upper:]]*)\b/PLEOKAK\n/gm;
s/^#PP:COPY\b/PLEOKAK\n\$compiled .= \$code;\n/gm;
s/^#PP:REWRITE\b(.*)/PLEOKAK\n{ $1 }\n\$compiled .= \$code;/gm;
s/^#PP:CODE\b//gm;
s/^#PP:IN\b/\$code = <<'PLEOKAK';/gm;
$src = $_;
#{ open my $fh, q[>], q[/tmp/kakinv.pl]; print $fh $src; }
eval $src; print $compiled;
